"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const taskController_1 = require("../controllers/taskController");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const taskRoutes = (0, express_1.Router)();
taskRoutes.route('/:board_id').post(authMiddleware_1.protect, taskController_1.addTask).patch(authMiddleware_1.protect, taskController_1.editTask);
taskRoutes.route('/:board_id/deleteTask').patch(authMiddleware_1.protect, taskController_1.deleteTask);
taskRoutes.route('/:board_id/subtask').patch(authMiddleware_1.protect, taskController_1.updateSubTask);
exports.default = taskRoutes;
